export enum ErrorTypes {
  CARDS_MUST_BE_REMOVED = 'Eldest hand must remove cards before opening trick',
  CARD_NOT_FOUND = 'Card not found',
  CURRENT_HAND_NOT_FINISHED = "Can't start new hand when current is ongoing",
  FORBIDDEN = 'Forbidden operation',
  GAME_ENDED = 'Game has ended',
  GAME_NOT_FOUND = 'Game not found',
  GAME_TYPE_CHOSEN = 'Game type is already chosen',
  GAME_TYPE_NOT_CHOSEN = 'Game type is not chosen yet',
  ILLEGAL_CHOICE = 'Illegal game type choice',
  INVALID_GAME_ID = 'Invalid game identifier',
  MUST_BE_ELDEST_HAND = 'Operation not allowed: player must be eldest hand',
  MUST_FOLLOW_SUIT_AND_TRUMP = 'Suit and trump suit must be followed',
  NOT_FOUND = 'Not found',
  NOT_TRICK_LEAD = 'Player is not trick lead',
  NO_MORE_CARDS_TO_REMOVE = 'No more cards to be removed',
  OTHER_PLAYER_HAS_TURN = 'Other player has a turn',
  PLAYER_NOT_IN_GAME = 'Player is not in the game',
  RECOVERY_SENT = 'Recovery SMS is already sent',
  TRICK_ALREADY_STARTED = 'Trick is already ongoing',
  TRICK_NOT_STARTED = 'Trick is not started yet',
}
